### PR TITLE
Version one test runner

### PR DESCRIPTION
**Pull request by ErikSchierboom**
@lucaferranti I'm trying to build a test runner for the Chapel track. All went smooth until I tried to run `mason test` within the test runner. It gives me the following error message:

> Mason could not find your configuration file (Mason.toml)

However, if I do an `ls` in the directory from which I run `mason test` I _do_ see a `Mason.toml` file with the following contents:

```toml
[brick]
name="example-success"
version="0.1.0"
chplVersion="1.28.0"
type="application"
```

Any idea?

### CODE REVIEW

**Comment by lucaferranti** [comment]
Thank you @ErikSchierboom for the help, I'll admit I was a little stuck with this :) 

I'll try to have a look later today, but it seems a great step forward, this gives me hope we'll actually manage to launch this soon :)

**Comment by ErikSchierboom** [comment]
@lucaferranti Did you by any chance had the opportunity to look at this?

**Comment by lucaferranti** [comment]
@ErikSchierboom not yet unfortunately :/

I'll try to have a look at this during the upcoming week.

sorry for the slow follow-up with this

**Comment by ErikSchierboom** [comment]
No problem

**Comment by ErikSchierboom** [comment]
@lucaferranti Small bump to check if you've managed to find anything that was causing the issue?

**Comment by lucaferranti** [comment]
sorry for the long radio silence. I was travelling for work last week. I'll try to have a look this weekend

**Review by kytrinyx — APPROVED** [review]

**Review by kytrinyx — APPROVED** [review]

**Review by kytrinyx — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@lucaferranti Any chance you'll be able to look at this PR?

**Comment by ErikSchierboom** [comment]
@lucaferranti I managed to fix the test runner by upgrading!

**Pull request merged**
