### PR TITLE
Add initial version

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@lucaferranti This is a first, working version of the test runner. The setup is such that we have a couple of test cases in `tests/` for various scenarios (like all tests passing or a syntax error, etc.) You can run the tests locally via `./bin/run-tests-in-docker.sh`, which will build the docker image we'll use to deploy and verify that the produced `results.json` files match the `expected_results.json` files.

**Comment by ErikSchierboom** [comment]
@lucaferranti I've also fixed the Docker hub part of the deploy workflow: https://github.com/exercism/chapel-test-runner/actions/runs/7971189533

For now, this means that the test runner should be working well enough to deploy in production once the track is ready, so your focus can be on the other tasks of the track (not sure what the status is).

Once we're in the "let's have a select few people test the track" phase, I'll make sure the test runner is deployed to AWS too (which it currently is not: https://github.com/exercism/chapel-test-runner/actions/runs/7971189533/job/21760342924)

**Comment by lucaferranti** [comment]
@ErikSchierboom  Thanks, I have a question about the "well enough" though.

Are there any tracks that are satisfied with tier 1 for the test runner? Do you have any insights on how is the user experience of tier 2 vs tier 1?

**Comment by ErikSchierboom** [comment]
> Are there any tracks that are satisfied with tier 1 for the test runner?
It's what the majority of tracks use I estimate.

> Do you have any insights on how is the user experience of tier 2 vs tier 1?

The main difference is in how things are presented in the online editor. For version 1, we can only show a text message explain what went wrong (or a success state). For version 2, we can list the individual test cases and show which ones are passing and which ones aren't.

**Pull request merged**
